# ベースイメージとしてPostgreSQLを使用
FROM postgres:13

# 環境変数（DB初期化用）
ENV POSTGRES_DB=ims
ENV POSTGRES_USER=postgres
ENV POSTGRES_PASSWORD=2wsx!QAZ

# 必要に応じて、初期化スクリプトを追加
COPY ./src/main/resources/schema.sql /docker-entrypoint-initdb.d/schema.sql
COPY ./src/main/resources/data.sql /docker-entrypoint-initdb.d/data.sql

EXPOSE 5432