# ベースイメージとしてOpenJDK 17を使用
FROM openjdk:17-jdk-slim

RUN apt-get update && \
    apt-get install -y fonts-dejavu fonts-liberation fontconfig fonts-ipafont && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/* && \
    fc-cache -f -v

# 環境変数としてJARファイル名を定義
ENV APP_JAR=inventorymgmtsys-0.0.1-SNAPSHOT.jar

# 作業ディレクトリを設定
WORKDIR /app

# アプリケーションJARをコンテナ内にコピー
COPY target/${APP_JAR} /app/app.jar

# コンテナ起動時のエントリポイント
ENTRYPOINT ["java", "-Djava.awt.headless=true", "-jar", "/app/app.jar", "--spring.profiles.active=staging"]

EXPOSE 8080